implement autocomplete functionality
chingu-voyages/v52-tier3-team-39 pull request #43
Opened 2024-11-17 16:06 UTC by adbshiau

…ddress validation

2024-11-17 20:54 UTC, DalySoftware requested changes

2024-11-18 07:11 UTC, tdkent commented on client/components/AutocompleteAddress.jsx
> +  const addresses = [];
Fixed

2024-11-18 07:13 UTC, tdkent commented on client/components/AutocompleteAddress.jsx
> +    fetchAddresses();
We moved the address autoComplete function to a separate `useEffect` with the addresses state as a dependency to resolve this

2024-11-18 07:23 UTC, tdkent commented
Made some minor changes to cleanup/clarify auto-complete logic without changing functionality. Also fixed a couple of minor unrelated bugs.

2024-11-18 07:23 UTC, tdkent approved these changes

2024-11-18 07:23 UTC, merged