Admin dashboard
chingu-voyages/v52-tier3-team-39 pull request #56
Opened 2024-11-27 00:35 UTC by kristi-h

2024-11-27 20:32 UTC, DalySoftware requested changes

2024-11-27 20:32 UTC, DalySoftware commented on client/app/admin-dashboard/page.jsx
> +        <ReservationTable />
ReservationTable is still making a separate fetch internally. I think it'd make more sense if it also accepted an appointments prop

2024-11-27 20:32 UTC, DalySoftware commented on client/components/admin_dashboard/.Map.jsx.swp
I don't think this is supposed to be committed

2024-11-27 20:32 UTC, DalySoftware commented on server/src/controllers/appointments.controller.js
> +    }
Quite weird to throw an error then immediately re-catch it. Would suggest if you want to throw something like this, it should be outside the try catch

2024-11-27 23:19 UTC, DalySoftware submitted a review, later dismissed

2024-11-28 00:02 UTC, DalySoftware approved these changes

2024-11-28 00:36 UTC, tdkent commented
I can assume it's all working,  but since the Google API key(s) have not been shared, I can't see the map or test the geocoding

2024-11-28 01:17 UTC, merged