Sort algo
chingu-voyages/v52-tier3-team-39 pull request #92
Opened 2024-12-16 22:27 UTC by kristi-h

add back sort with grasshopper api key

2024-12-18 02:47 UTC, kristi-h commented
admin_dashboard PR should get approved first.
I need to fix conflicts in this one.

2025-01-06 06:55 UTC, DalySoftware reviewed
For file renames, I'd highly recommend strictly keeping them to a standalone commit, and consider even a standalone PR for them. It's very hard to read diffs with both renames and changes, and easy to lose code. Bear in mind that a lot of devs barely review PRs before hitting approve, so you might not have as much safety as you think.

2025-01-06 06:55 UTC, DalySoftware commented on client/actions/form.js
> +    // console.log("respStatus", response.status);
```suggestion
```

2025-01-06 06:55 UTC, DalySoftware commented on client/actions/form.js
> +        scheduledDate: new Date(item.schedule?.scheduledDate),
I don't think this ? accessor makes sense. If schedule is nullish, you'll have `new Date(null)`, which apparently evaluates to the UNIX epoch.

If the schedule in the response is genuinely allowed to be missing, I think it makes more sense to omit the whole object. If it's not allowed to be missing then we have to handle the error in some way when `item.schedule == null`

Judging by this code from the client `valueGetter: (_, row) => row.schedule.scheduledDate,` it's not allowed to be missing.

2025-01-06 06:55 UTC, DalySoftware commented on client/components/admin-dashboard/Grid.jsx
> +};
Appears to duplicate all the code in formatters.jsx (which can still be renamed to formatters.js btw)

2025-01-06 06:55 UTC, DalySoftware commented on client/components/admin-dashboard/Map.jsx
> +  console.log("map", appointments);
Debug code, presumably should be removed

2025-01-06 06:55 UTC, DalySoftware commented on client/components/admin-dashboard/Map.jsx
> +  // console.log(appointments[0]);
```suggestion
```

2025-01-06 06:55 UTC, DalySoftware commented on client/components/admin-dashboard/Grid.jsx
> +export default function Grid({ rows }) {
Is this whole file a bad merge? It's different to main. The `toggleVisited` stuff is gone too

2025-01-06 18:52 UTC, kristi-h commented on client/components/admin-dashboard/Grid.jsx
> +};
oh no, I think what I modularized into smaller components came back into Grid with the merge..I'll go back and erase the extras.

2025-01-06 19:25 UTC, kristi-h commented on client/actions/form.js
> +    // console.log("respStatus", response.status);
gotcha~ good point.

2025-01-06 19:25 UTC, kristi-h commented on client/actions/form.js
> +        scheduledDate: new Date(item.schedule?.scheduledDate),
ah okay~

2025-01-06 19:40 UTC, kristi-h commented on server/src/scheduling/scheduler.js
> +    if (order > 0) {
ahh.. right~

2025-01-06 20:59 UTC, DalySoftware requested changes

2025-01-06 20:59 UTC, DalySoftware commented on server/src/scheduling/scheduler.js
> +    throw new Error(`Couldn't connect to graph hopper: ${response.status}`);
```suggestion
    throw new Error(`Couldn't connect to graph hopper: ${resp.status}`);
```
`response` doesn't exist

2025-01-06 21:19 UTC, DalySoftware approved these changes

2025-01-06 21:31 UTC, merged